# Generated by Django 2.0.2 on 2018-02-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20180221_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='googledrive_refresh',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='googledrive_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dropbox_token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
