# Generated by Django 2.0.2 on 2018-02-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_auto_20180224_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='googledrive_token_time',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
